### ISSUE TITLE
[RR} Room Management installation error

### ISSUE THREAD

**Issue by marcierempel** [CentralAZ/Rock-CentralAZ#100]
I just installed the Room Management plugin on our live site (running v8.5) today. I received the following error on the page when I tried to open it. The only thing I did was change the security settings on the page to only allow to security groups to view it. Can someone get back to me ASAP please? I've been running this on our development site and it's been working fine.
[Room Management Plugin error.pdf](https://github.com/CentralAZ/Rock-CentralAZ/files/2766254/Room.Management.Plugin.error.pdf)

### Prerequisites
* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

A clear and concise description of what the bug is, include screenshots if applicable.

### Steps to Reproduce

**Expected behavior:**

**Actual behavior:**

A description of what actually happened.

### Versions

* **Rock Version:** [Enter Rock version here]
* **Client Culture Setting:** [Enter Client Culture here]

**Comment by marcierempel** [comment]
Today when I logged in to Rock, the Room Management page was working. I had cleared the cache and restarted Rock when I installed it so I'm not sure what changed. Can someone help me understand what happened there?

**Comment by nairdo** [comment]
Hi @marcierempel Can you copy all the text of that error page into here? The screenshot in the PDF you attached has the most important parts of the line cut off -- so we really can't tell where the error is happening for you.

Also, have you enabled the Lava EntityCommands on your production server as mentioned in the installation steps of the admin guide?

**Comment by marcierempel** [comment]
Hi Nick, it worked today when I opened it so I’m not sure what happened before. You can close the ticket.

Marcie Rempel | EXECUTIVE ASSISTANT
Sherwood Park Alliance Church | spac.ca<http://www.spac.ca/>
780.467.8404 x420
