### ISSUE TITLE
[RR} Enhancement - schedule date and times connected to each location 

### ISSUE THREAD

**Issue by marcierempel** [CentralAZ/Rock-CentralAZ#101]
We would love to be able to have multiple locations within one reservation that would allow different times/dates for each location. For example: if we have a large event that requires the caterers to use our kitchen for a full day, but the event that's taking place in the auditorium is only scheduled for 3 hours, we would like to keep those times for each location separate.

# Feature Request

**Describe the Feature Request**

**Describe Preferred Solution**

**Describe Alternatives**

**Providing Code**
I will provide code if feature request is approved: [Yes/No]

**Comment by nairdo** [comment]
Sorry, the system only supports a reservation having a single schedule. I'd recommend setting up an additional reservation for other events related to the main reservation.
