### ISSUE TITLE
[RR] When adding event via Available Resources option Resources screen is missing all resources

### ISSUE THREAD

**Issue by jarvisington** [CentralAZ/Rock-CentralAZ#102]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site] - Room Management didn't seem to be on demo site. (http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description
When doing a new reservation via the **Available Resources** Top menu item the Resources list appears empty.  User must toggle **Show All Resources** on then off to view the resources of selected campus. 

### Steps to Reproduce

1. Click the **Intranet Icon** > **Room Management**
2. Choose **Available Resources** from the top menu
3. Choose a **location** by clicking on it 
4. Choose a **Campus** from the dropdown
5. Expand **Resources** box (if necessary)
6. Click **( + )** button to add a new resource
7. Click **Resource** dropdown to view resources for the selected campus
8. This list is empty.  User must click **Show All Resources** which loads all the resources, then uncheck it to show only the resources for selected campus. 

**Expected behavior:**

My Expectation is that on step 7 above - the window that pops up would have the resources for the selected campus as it does in the when choosing **New Reservation** on the top menu instead of **Available Resources** 

**Actual behavior:**

See **Step 8** in **Steps to Reproduce**: The **Resource** window appears blank initially and only populates after checking the **Show All Resources** checkbox and unchecking it again.

### Versions

* **Rock Version:** Rock Version: Rock McKinley 8.5 (1.8.5.2)
* **Client Culture Setting:**
Windows 10, Chrome Version 71.0.3578.98 (Official Build) (64-bit)
[Room Management Documentation.docx](https://github.com/CentralAZ/Rock-CentralAZ/files/2769554/Room.Management.Documentation.docx)

**Comment by tcavaletto** [comment]
Fixed in v1.3.3
