### ISSUE TITLE
Approve/Deny buttoms not displaying properly

### ISSUE THREAD

**Issue by jrockman13** [CentralAZ/Rock-CentralAZ#103]
### Prerequisites
* [ X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

The approve Deny buttons are not displaying correctly. Multiple churches have noticed the same issue.

### Steps to Reproduce

Create a new reservation and choose rooms that require approval OR open a reservation that has rooms/resources with pending approvals. Note that the buttons do not show completely.

I
![approve-btn1](https://user-images.githubusercontent.com/22159658/51551760-c6907780-1e34-11e9-9d2a-99492cde9064.JPG)
![approve-btn2](https://user-images.githubusercontent.com/22159658/51551761-c6907780-1e34-11e9-9ea0-3e1dd1d7c49a.JPG)

'm running on Windows 10. 24" 1920x1080 monitor. no scaling enabled. Using Chrome browser v71. Tried using the device toolbar and tested on IPad, Google Pixel 2, and responsive. Shutting off device toolbar and free resizing from full-screen to tiny makes no difference 

**Expected behavior:**

Approve/ deny buttons should display properly.

**Actual behavior:**

See screenshots

### Versions

* **Rock Version:** [8.5]
* **Client Culture Setting:** [en-us]

**Comment by MicahO** [comment]
Can confirm we see the same behavior, regardless of monitor size or resolution.

**Comment by mswartztex** [comment]
I found 1 monitor in which it (resource area) displays correctly.  The Location area still does not.
![image](https://user-images.githubusercontent.com/43970752/55964341-28919980-5c3a-11e9-9ab0-cbf0db1bdb9b.png)

This monitor is a Dell 1704 (Wide Screen) Resolution at 1280x1024.

**Comment by tcavaletto** [comment]
Fixed in 1.4.0: https://github.com/CentralAZ/Rock-CentralAZ/commit/98162a110247385f541a19a03f79f59326cd56ae
