### ISSUE TITLE
[RR] Delete Reservation Option

### ISSUE THREAD

**Issue by gracechurch360** [CentralAZ/Rock-CentralAZ#104]
### Prerequisites
* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

As of Rock 8.4 we lost the ability to delete a room reservation. I'm not sure if it's related to Rock V8.4 or the plugin.
Cheers.

### Versions

* **Rock Version:** [8.4]
* **Client Culture Setting:** [Enter Client Culture here]

**Comment by eddieholeman** [comment]
@gracechurch360 we are on Rock 8.5 and still have a delete option.  Could this be a security issue?

**Comment by nairdo** [comment]
Thanks for bringing this up! With the latest version of the plug-in we did enhance who can delete a reservation.  I need to add this to the documentation, but the rules are:

- if the person canApprove the reservation
- or if the CurrentPerson created the reservation
- or if the CurrentPerson is the reservation.AdministrativeContactPerson
- or if the reservation type has granted the 'can delete' role to the person.

Hopefully this makes sense but please let me know if you are not able to to follow my cryptic notes. _(typing via my phone while out of the office)_

**Comment by eddieholeman** [comment]
@nairdo Thanks Nick.  That helps a bunch.
