### ISSUE TITLE
Reservation reminders should go to Administrative Contact or Event Contact, not Contact Creator

### ISSUE THREAD

**Issue by MicahO** [CentralAZ/Rock-CentralAZ#107]
### Prerequisites
Searched existing bug database, Rock version is Rock McKinley 8.5 (1.8.5.2) // en-US, but problem cannot be reproduced in demo site because demo site does not have this plugin.

### Description

Event reminders are always sent to the person who originally created the event, even if the administrative contact is changed.

### Steps to Reproduce

1. Create an event with Person A.
2. Change Event Contact and Administrative Contact to a new person.
3. Select a room or resource that can easily be approved, then approve that resource.
4. See that the notification is returned to the event creator, not to the Event Contact or Administrative Contact.

**Expected behavior:**

Notifications should be sent either to the Event Contact or Administrative Contact. Not to the original event creator, which cannot be changed.

**Actual behavior:**

Notifications are sent to the event creator, even if the Event Contact and Administrative Contact are changed.

### Versions

* **Rock Version:** Rock McKinley 8.5 (1.8.5.2). Room Managment Plugin version 1.3.2.
* **Client Culture Setting:** en-US

**Comment by tcavaletto** [comment]
In the Room Reservation Reminder Notification workflow type, what does your Set Email To action look like?

**Comment by MicahO** [comment]
In the "Set Email To" action, the text value is 

{% assign Reservation = Workflow | Attribute:'Reservation','Object' %}{{ Reservation.EventContactEmail }}

That should be right... event contact is what I want. But for some reason it's passing Event Creator instead?

**Comment by MicahO** [comment]
Re-discovered this bug in a new way today. We have a weekly "Celebrate Recovery" group that meets on Wednesday nights. It has been growing, so I edited the reservation to add more chairs.

The event was originally created by a volunteer over a year ago. They're no longer volunteering in that capacity. But the approval email that Rock generated said that the request came from them, which really confused our Facilities team.

If someone updates the event, shouldn't the new request look like it comes from them?

**Comment by tcavaletto** [comment]
The Email Reminder is fixed as of 1.4. Since we're making big changes to the Approval workflow in 1.5, I've added an item there to use the admin contact instead of the requester. https://github.com/CentralAZ/Rock-CentralAZ/issues/128
