### ISSUE TITLE
Can't change reservation type...

### ISSUE THREAD

**Issue by sanford-rock** [CentralAZ/Rock-CentralAZ#108]
### Description
Can't change the reservation type on an existing RM reservation, When you go into Edit mode for a reservation and put the mouse pointer on the reservation type it displays and icon, do not enter wrong way type sign, and the field is not available to click into. I have to change reservation types with SQL.

* **Rock Version:** [8.4]
* **Client Culture Setting:** [Enter Client Culture here]

**Comment by nairdo** [comment]
Sorry @sanford-rock Changing reservation types on existing reservations won't work and is not supported.
