### ISSUE TITLE
Feature Request: Calendar View

### ISSUE THREAD

**Issue by MicahO** [CentralAZ/Rock-CentralAZ#109]
# Feature Request

**Describe the Feature Request**
The list-based view of events is often useful, but it would also be very handy to have a calendar-based view.

**Describe Preferred Solution**
A calendar view would be a page/block that showed a monthly calendar with each day's events listed on that day of the calendar. Since moving to Room Management from our previous tool (PCO Resources) this is our biggest request from staff and volunteer teams.

**Describe Alternatives**
None at this time.

**Providing Code**
No.

**Comment by jeremyhoff** [comment]
To add to this, the calendar page should include:
. per-event clickable links directly to the reservation

Bonus points if possible, to bring feature-parity for EMS users (pending U/I restraints):
. if security permits, hover over event to reveal icon to duplicate reservation
. if security permits, hover over event to reveal icon to delete reservation

**Comment by megilee** [comment]
Check out this recipe from Luke Bennett: https://community.rockrms.com/recipes/112/room-management-calendar-view

**Comment by tcavaletto** [comment]
Added in https://github.com/CentralAZ/Rock-CentralAZ/commit/a83001b4988302281b331d61bfe685f9dadbc245
