### ISSUE TITLE
Feature Request: Easily expose start and end dates

### ISSUE THREAD

**Issue by MicahO** [CentralAZ/Rock-CentralAZ#110]
# Feature Request

**Describe the Feature Request**
When an event is scheduled weekly for, say, 12 weeks, there is no simple way for people without edit permissions to see the date on which the recurring event starts.

**Describe Preferred Solution**
Display start and end dates when displaying the schedule. For example consider changing

Schedule
Weekly: Tuesdays at 6:00 PM for 2 hrs

to

Schedule
Weekly: Tuesdays at 6:00 PM for 2 hrs (2-5-19 to 4-30-19)

Currently, the only way to find the start and end date is to edit the schedule. This means no one with view-only access can find the start and end date without poking through the calendar a week at a time.

**Describe Alternatives**
Open to alternate solutions, but this seems easiest because it's not changing anything internal; just changing the way the schedule is displayed. Ideally, this would be included in the scheduling email as well.

**Providing Code**
No.

**Comment by tcavaletto** [comment]
Note: We should also add exclusion dates to this. We can have a more detailed FriendlyScheduleText than normal display the information on the reservationDetail page, and have the normal one display elsewhere for the sake of space.
