### ISSUE TITLE
Feature Request: See all reservations needing my approval

### ISSUE THREAD

**Issue by MicahO** [CentralAZ/Rock-CentralAZ#111]
# Feature Request

**Describe the Feature Request**
There is not currently an easy way for a specific person to find out all of the rooms/resources that currently need their approval. The only solutions currently are for that person to search their email inbox or to filter for all unapproved events and mentally screen for rooms/resources that they have approval permissions for.

**Describe Preferred Solution**
Ideally there would be a block on their Rock dashboard that could show all of the events currently needing their approval, as well as a tab in the Room Management module with the same information.

**Describe Alternatives**
None come to mind.

**Providing Code**
No.

**Comment by tcavaletto** [comment]
Added to 1.4: https://github.com/CentralAZ/Rock-CentralAZ/commit/f88e6f0ee365819d6220bf0c406fcb9180089a23
