### ISSUE TITLE
Feature Request: Automatic vCal/iCal generation with new event

### ISSUE THREAD

**Issue by MicahO** [CentralAZ/Rock-CentralAZ#112]
# Feature Request

**Describe the Feature Request**
It would be awesome if a new reservation generated a matching vcal/ical event that could be clicked and added to a person's calendar.

**Describe Preferred Solution**
An icon somewhere on the Room Management reservation that included a link to a calendar invite.

**Describe Alternatives**
None come to mind.

**Providing Code**
No.

**Comment by tcavaletto** [comment]
Added to 1.5.4
