### ISSUE TITLE
[RR] Specify Which Room Requires Using the Final Approval Group

### ISSUE THREAD

**Issue by edcylam** [CentralAZ/Rock-CentralAZ#116]
# Feature Request

**Describe the Feature Request**
There are several major rooms, such as the Worship Center, in our building that we want closer scrutiny before approving people to use them. 

**Describe Preferred Solution**
One idea is to specify which rooms are required using the Final Approval Group in the Reservation Type Detail in the approval process. 

**Describe Alternatives**

**Providing Code**
I will provide code if feature request is approved: No

**Comment by tcavaletto** [comment]
Currently you're able to add an additional approval group onto locations such as the Worship Center so that the location requires special approval prior to the reservation landing on the final approval group's desk. How are you thinking the process would be modified?

**Comment by tcavaletto** [comment]
Closed due to inactivity
