### ISSUE TITLE
Feature Request: Track Emails in Communication History

### ISSUE THREAD

**Issue by MicahO** [CentralAZ/Rock-CentralAZ#118]
# Feature Request

**Describe the Feature Request**
Emails sent by Room Management are not currently tracked in Rock's Communication History tracker. This makes it difficult to troubleshoot problems, since there's no history to draw on. We would like to see email history turned on by default.

**Describe Preferred Solution**
When the Room Management plug-in sends emails via Rock (for approval, reminders, etc) they should show up in Rock's Communication History.

**Describe Alternatives**
As an alternative, we could instead provide the option to track certain types of emails, or even emails associated with individual events.

**Providing Code**
I will provide code if feature request is approved: [Yes/No]
No

**Comment by tcavaletto** [comment]
Marked 1.5. We're going to create a workflow action to send emails to location/resource approval groups so we can pull that logic out of the block, so we'll update the workflow at that point to save everything to the person's record. In the meantime, you can modify the workflow you use to have any SendEmail action save the email to the person's history.
