### ISSUE TITLE
Locations Greyed Out in Room Reservation

### ISSUE THREAD

**Issue by edcylam** [CentralAZ/Rock-CentralAZ#120]
Before completing your first issue we highly recommend reading this post on [Effective Ways To Get Help from Maintainers](https://www.snoyman.com/blog/2017/10/effective-ways-help-from-maintainers).

### Prerequisites
* [x] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

Locations/rooms in New Reservation are all greyed out (plug-in version 1.3.3)

### Steps to Reproduce

1. Make a new reservation
2. Pick a schedule
3. Selection a location

**Expected behavior:** 

The text of all locations should be black.

**Actual behavior:** 

Some locations are in middle grey, and some others in light grey. All locations seem to be still clickable. But users may think that they aren't available.

![Screen Shot 2019-04-26 at 4 38 55 PM](https://user-images.githubusercontent.com/24534451/56842417-b4661100-6849-11e9-9ecb-af46dc0eb9b1.png)

### Versions

* **Rock Version:** [8.7]  
* **Client Culture Setting:** [en-us]
  <a href="https://www.rockrms.com/github-detect-client-culture-setting" target="_blank">unsure? detect what yours is here (right click and open in new window)</a>

**Comment by tcavaletto** [comment]
Fixed in https://github.com/CentralAZ/Rock-CentralAZ/commit/4dbc6b3739beeb25225ea50866bc909135ca993d
