### ISSUE TITLE
[RR] Ministry Filters

### ISSUE THREAD

**Issue by marcierempel** [CentralAZ/Rock-CentralAZ#121]
The ministry filter areas are showing duplicates. When we added ministries to each reservation type, they are now duplicated in both the search reservations page and the main room management page block. Can this be fixed?

![image](https://user-images.githubusercontent.com/44587882/57304891-592fec00-709d-11e9-9c06-8fc4de017f30.png)

![image](https://user-images.githubusercontent.com/44587882/57304923-68af3500-709d-11e9-9b1f-681f13571938.png)

**Comment by tcavaletto** [comment]
We'll fix this be grabbing distinct names and filtering off of those.

**Comment by tcavaletto** [comment]
Fixed in 1.4: https://github.com/CentralAZ/Rock-CentralAZ/commit/2f075363adb1a480c574ae6e0e9d1b3f73d81314
