### ISSUE TITLE
Reservation Detail schedule view

### ISSUE THREAD

**Issue by marcierempel** [CentralAZ/Rock-CentralAZ#122]
We would appreciate being able to see the day or date on a reservation after it's been booked, as well as if it's recurring or not. The reason is, when a staff member wants to book the same room, that's already booking on a recurring schedule, they could better see the dates they could put in for exceptions, making the room available for them to book.

![Reservation](https://user-images.githubusercontent.com/44587882/57703776-f353df00-761d-11e9-9c0f-73b32fb3feee.jpg)

**Comment by daniellevos** [comment]
My staff would love this too! They are complaining about not having an easy way to view the dates/times of the reservation without going in to the edit screen and doing the calculations

**Comment by tcavaletto** [comment]
This request is similar to https://github.com/CentralAZ/Rock-CentralAZ/issues/110, so we're closing it and adding a note to fast-track that feature.
