### ISSUE TITLE
Dashboard to view all my reservations

### ISSUE THREAD

**Issue by daniellevos** [CentralAZ/Rock-CentralAZ#124]
We would love to have a dashboard for the logged in user to view all of their upcoming reservations. Currently we have to go search for reservations created by the user.

**Comment by MicahO** [comment]
Hi Daniel. I completely agree; this would be very helpful. Do me a favor and check this out: 

https://github.com/CentralAZ/Rock-CentralAZ/issues/111

Are we asking for the same thing?

**Comment by tcavaletto** [comment]
Added to 1.4: https://github.com/CentralAZ/Rock-CentralAZ/commit/f88e6f0ee365819d6220bf0c406fcb9180089a23
