### ISSUE TITLE
Update Approval workflow to use Admin Contact instead of Requester, as well as include info about the event contact.

### ISSUE THREAD

**Issue by tcavaletto** [CentralAZ/Rock-CentralAZ#128]

**Comment by megilee** [comment]
We would like to request the option to send the approval notifications to the Event Contact. We are currently using the system with staff entering the reservations as the Admin Contact (whom may or may not be in the approver group). The Event Contact may or may not be a staff member (e.g. Attendee reserving room for baby shower). We would like an automated email notification letting both the Admin and the Event Contact know when their reservation has been approved or denied. Thank you for your great plugin!

**Comment by tcavaletto** [comment]
Fixed in https://github.com/CentralAZ/Rock-CentralAZ/commit/7cce30eed0a168f8a6a268cbeffa9c1c6725ac57. To also send to the Event Contact, you can:
1) Copy the workflow
2) Copy the Admin Contact attribute and actions
