### ISSUE TITLE
Attributes not showing prior to save

### ISSUE THREAD

**Issue by MCoulterFBCN** [CentralAZ/Rock-CentralAZ#131]
### Description

With the latest update of the Room Management plug-in, while it allows for attributes to be added, they do not show up on the initial entry page for an event.  So it appears you must first save an event then return to edit it and the attributes then appear.  Not sure if this is by design but for us we are hoping to streamline the entry process and have those questions answers on the initial entry.

### Steps to Reproduce

1. Go to Room Management
2. Click New Reservation
3. Notice only native Event fields exist
4. Save a new reservation 
5. Return to edit the reservation and see that now the attributes are available at the bottom.

**Expected behavior:**

We would expect those fields to exist when viewing the New Reservation screen and also expect them to dynamically change by selecting a reservation type in the drop down field.  We are hoping for as few steps as possible.  

**Actual behavior:**

You must enter the basic fields for an event/reservation then go back to it, click edit, then modify the additional attribute information.

### Versions

* **Rock Version:** 9.2
* **Client Culture Setting:** en-US

**Comment by coreydwillis** [comment]
We are experiencing the exact same issue.

**Versions**
Rock Version: 8.9
Client Culture Setting: en-US

**Comment by BEGamache** [comment]
Noticed the same in our 9.2 instance.

As an enhancement, if attributes become available when setting up a new reservation, could we pass in attribute values though url parameters if the keys match? I think this would be useful for us when we use our Event Planning Form (workflow), and when the event form is approved the staff is then asked to set up their reservation through a button in the workflow which will direct the staff user to the reservation entry page with the workflow's Id in the parameter which will then link the approved form to the reservation's attribute.

**Comment by jrockman13** [comment]
We also have this issue.....what could we do to help get this fixed? $$$ :-) Well, maybe just one $.

**Comment by megilee** [comment]
Us, too. Currently running Rock v9.4 and getting ready to update to v10.1.

**Comment by tcavaletto** [comment]
Fixed as of Room Management 5.0
