### ISSUE TITLE
[RR] Compatibility Issue with v10

### ISSUE THREAD

**Issue by BEGamache** [CentralAZ/Rock-CentralAZ#132]
### Prerequisites
* [x] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

When I was updating to v10 for alpha testing I ran into an issue with the Room Management plugin creating an error. v10 updated successfully, upon restarting I got the error message below. I thought it may have been an issue with me being on 1.3.1 instead of the new 4.1 version. I restored back to v9.2 and updated the plugin. I had a hard time with the plugin after updating it. When I went to the Room Management page I got an error for a null reference. In order for this to go away I had to restart the server. Room Management was working fine after the restart. I proceeded to update to v10. Once it finished, I clicked Restart and it reloaded the page. I was greeted with the error below, again. I removed the room reservation dll from the bin folder and v10 loaded fine with no issue. 

<img width="1640" alt="Screen Shot 2019-10-23 at 6 16 44 PM" src="https://user-images.githubusercontent.com/5738650/67524616-ac5f2080-f676-11e9-87f0-113bc16ed925.png">

**Expected behavior:**

Smooth install

**Actual behavior:**

Error in the dll. I had to remove the dll from the bin folder in order to access Rock.

### Versions

* **Rock Version:** v10 (alpha)
* **Client Culture Setting:** en-US

**Comment by marcierempel** [comment]
Do you know if this has been fixed with the early release of v10? I would like to install on our development site first to make sure I don't get the same errors as you, but do not know how to do everything you did to fix it.

**Comment by tcavaletto** [comment]
Fixed as of 1.5.0
