### ISSUE TITLE
[RR] Unable to create a Single-Select or Multi-Select Resource attribute question

### ISSUE THREAD

**Issue by BEGamache** [CentralAZ/Rock-CentralAZ#137]
### Prerequisites
* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

When we click the plus sign to add a resource question and set the Field Type to Single-Select or Multi-Select we get this error:
```
Error

53|error|500|Object reference not set to an instance of an object.|
```
The only way I can get around this is by creating the attribute as a text attribute and in the database update the field type to either a single select or multi select.

We are able to select other field types with no problem (haven't tried them all though) but when we attempt to use single or multi select we get an error and are unable to create or save the attribute.

### Steps to Reproduce

1. Go to a Resource and Edit it.
2. Add a question
3. Type in the question name or just try to change the field type to single or multi-select and see the error display on the page behind the attribute modal.

**Expected behavior:**

Able to select Single or Multi-Select.

**Actual behavior:**

Selecting Single or Multi-Select causes the error to occur.

### Versions

Room Management: 1.4.1
* **Rock Version:** 9.2
* **Client Culture Setting:** en-US

**Comment by azturner** [comment]
This issue was [reported here also](https://github.com/SparkDevNetwork/Rock/issues/3948). Note, you can work around this issue by first changing the field type to integer, and then selecting the Single/Multi select field type.

**Comment by BEGamache** [comment]
Thanks for pointing that out @azturner. I didn't think to check Rock's reported issues. Sorry for the duplicate issue.

**Comment by azturner** [comment]
@BEGamache I don't think it's necessarily a duplicate. The Room Management plugin could be updated to address this too.

**Comment by tcavaletto** [comment]
Fixed in https://github.com/CentralAZ/Rock-CentralAZ/commit/20ed020b046de9eb2121b5706e27ee00bd7bd9f7
