### ISSUE TITLE
[RR] Can't Save Default Reservation Type after 1.4.1 update

### ISSUE THREAD

**Issue by tscrip** [CentralAZ/Rock-CentralAZ#139]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description
We were using the default Reservation Type. We updated to 1.4.1, and now we can not save the Default Reservation Type. We get the error below.
![image](https://user-images.githubusercontent.com/7517351/71523372-4ec19d00-288e-11ea-87fc-562dfddc678a.png)

### Steps to Reproduce

1. Install Room Management Plugin before 1.4.1
2. Update Room Management Plugin to 1.4.1
3. Attempt to save 1.4.1 Default Reservation Type

**Expected behavior:**

Updating to 1.4.1 should not prevent you from saving the default template.

**Actual behavior:**

Updating to 1.4.1 prevents you from saving the default template.

### Versions

* **Rock Version:** 8.8
* **Client Culture Setting:** en-US

**Comment by tcavaletto** [comment]
Fixed as of 1.5.2
