### ISSUE TITLE
[RR] Feature Request: Make Reservation Attributes Conditional

### ISSUE THREAD

**Issue by asdf1nit** [CentralAZ/Rock-CentralAZ#145]
# Feature Request

**Describe the Feature Request**
I would like to propose the ability to make some attributes conditional similar to the way that registration attributes can be on event registration.

Example: You add an attribute asking if the doors need to be unlocked(if it's not typical time that that they are ) and if the answer is yes you have additional questions like what time and which doors that show up. Or maybe you have a question like: Will you have refreshments and they answer yes, you can ask additional questions about requirements for that.

**Describe Preferred Solution**
A filter option that shows up on the attributes panel of a Reservation type detail page that lets you make attributes conditional to other attributes values.

**Describe Alternatives**
A Pre-HTML and Post-Html field on attributes similar to a workflows Form action so we can add html\lava\javascript to the element to make attributes show and hide based on the selected value of other dom elements. I currently use this method on workflow UEFs.

**Providing Code**
I will provide code if feature request is approved: No.

**Comment by nairdo** [comment]
@asdf1nit Taylor and I looked at this but it's not really something we're going to be able to do at this time.  We're going to close this for now but we've labeled it as `not at this time` so we can easily find it later.
