### ISSUE TITLE
[RR] Null Reference Error when linked event is deleted from the Calendar page

### ISSUE THREAD

**Issue by BEGamache** [CentralAZ/Rock-CentralAZ#147]
### Prerequisites
* [x] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

When linking the Reservation to an event, if the event is deleted from the Calendar page, it causes an error when trying to view that Reservation through the Room Management detail page. It is throwing a null reference since the Reservation thinks the event still exists. An idea to fix this is to delete the event id from record and still load the reservation details, with the possibility of popping up a message saying the event was deleted and has been unlinked from the Reservation. The user should link to a new event if there is one.

<img width="2014" alt="Screen Shot 2020-03-04 at 3 05 36 PM" src="https://user-images.githubusercontent.com/5738650/75923167-258f3100-5e2a-11ea-9a9e-27102859c02e.png">

### Steps to Reproduce

1. Create a reservation.
2. Link to an existing Calendar Event or create a new one.
3. Delete the Calendar Event from the Calendar page from the internal site
4. Go back to the Reservation's detail page and see the error.

**Expected behavior:**

Access to the reservation details

**Actual behavior:**

Null Reference Error page

### Versions

* **Plugin Version:** 1.5.1
* **Rock Version:** 10.1
* **Client Culture Setting:** en-US

**Comment by nairdo** [comment]
Fixed in v1.5.2 by TC via https://github.com/centralaz/rock-centralaz/commit/dbe8e04a5c1689f40aa55326724eed827b2ca63e.
