### ISSUE TITLE
Add Separate default Setup and tear down times.

### ISSUE THREAD

**Issue by JoshuaMaiorino** [CentralAZ/Rock-CentralAZ#149]
# Feature Request

**Describe the Feature Request**
Add Separate default Setup and tear down times.

**Describe Preferred Solution**
Add Separate default Setup and tear down times.

**Describe Alternatives**
None?

**Providing Code**
No

**Comment by tcavaletto** [comment]
Closed as of https://github.com/CentralAZ/Rock-CentralAZ/commit/98ea9e25d15e9b7a5c5eb30e87a073eedd77a859
