### ISSUE TITLE
People Receive Emails after upgrading

### ISSUE THREAD

**Issue by tcavaletto** [CentralAZ/Rock-CentralAZ#168]
### Prerequisites
* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

A clear and concise description of what the bug is, include screenshots if applicable.

### Steps to Reproduce

**Expected behavior:**

**Actual behavior:**

A description of what actually happened.

### Versions

* **Rock Version:** [Enter Rock version here]
* **Client Culture Setting:** [Enter Client Culture here]

**Comment by marcierempel** [comment]
This happened to us as well. It took past reservations (looks like almost all of them going back to when we installed the plugin) and changed the status on all of them back to Pending Review - that means that everyone received a notification and we have to go back and approve all of them - which means everyone will receive another email.

**Comment by tcavaletto** [comment]
@marcierempel Could you give me a screenshot of the history on one of these reservations? I'll be digging into this issue this weekend and a reference point would be extremely helpful.

**Comment by marcierempel** [comment]
![Room Reservation status change](https://user-images.githubusercontent.com/44587882/84199178-ec3a1300-aa61-11ea-8f7f-11a2f57fbe69.JPG)

I wondered if it had something to do with the Populate FirstOccurrenceStartDateTime and LastOccurrenceEndDateTime fields on the Reservation table - job that ran. I don't remember seeing that job before the update to 1.5.2. 

It changed the statuses on over 750 reservations, but I'm having a hard time determining if it was only reservations that were approved already. It doesn't look like it touched any that had been denied. I'm trying to figure out a way to get all of them back in to the correct status.

**Comment by marcierempel** [comment]
![Room Reservation status change2](https://user-images.githubusercontent.com/44587882/84199880-1d671300-aa63-11ea-9719-d76dd6bcf782.JPG)

**Comment by tcavaletto** [comment]
This issue is now resolved and will be rolled into the next update.

**Comment by tcavaletto** [comment]
@marcierempel ++ for nailing where the source of the problem was.

**Comment by marcierempel** [comment]
@tcavaletto Do you know if it only changed the status of approved reservations back to pending review or did it change all reservations despite their current status? we're trying to figure out a way to get everyone of them back to what their status was before the job ran.
