### ISSUE TITLE
Spiritual Gifts badge hover

### ISSUE THREAD

**Issue by nairdo** [CentralAZ/Rock-CentralAZ#17]
On hover, show the name of their primary gifting.

See ideas on this page for bordered / encapsulated Spiritual Gifts badges that are made via standard Font Awesome stacking: http://rock.centralaz.com/page/408

(See the Stacked Icons section on this page: https://fortawesome.github.io/Font-Awesome/examples/)

Unfortunately, trying to use standard FA stacking technique causes the badge to look too small and it's also not aligned.  It may require some custom CSS to get it to align/size correctly.

**Comment by tcavaletto** [comment]
Also show a border font awesome icon

**Comment by nairdo** [comment]
We'll leave the icon stacking idea for another enhancement (feature request) and consider this issue "hover" closed now.
