### ISSUE TITLE
TakeProfilePhoto for iPhone/iPad

### ISSUE THREAD

**Issue by nairdo** [CentralAZ/Rock-CentralAZ#20]
Seamlessly integrate David Walsh's technique into our TakeProfilePhoto block so that it works (sort-of, but sort of different) for iPhone and iPad: http://davidwalsh.name/html5-camera-video-iphone

It just can't break the devices that currently work ([listed here](https://github.com/CentralAZ/Rock-CentralAZ/wiki/Widgets#tested-on)).

**Comment by tcavaletto** [comment]
Fixed in https://github.com/CentralAZ/Rock-CentralAZ/commit/ccf4607ad801cedf269992d9ad473225f3a44db8
