### ISSUE TITLE
eAccountability notify group members email is failing

### ISSUE THREAD

**Issue by nairdo** [CentralAZ/Rock-CentralAZ#23]
I can see in the system jobs section that they are getting clogged and failing (http://rock.centralaz.com/page/115?serviceJobId=9) for some reason.  Here's an example: http://rock.centralaz.com/Communication/216389

**Comment by tcavaletto** [comment]
Fixed in https://github.com/CentralAZ/Rock-CentralAZ/commit/6143f8461388c5c8dfcd87e088c384b815a3dcf8
