### ISSUE TITLE
HTML markup showing up in website search results

### ISSUE THREAD

**Issue by sparkdevnetwork-service** [CentralAZ/Rock-CentralAZ#29]
Not sure how this is happening, but when I search for something such as "share your faith" I'm seeing HTML in the search results:

![image](https://cloud.githubusercontent.com/assets/6056081/13200741/b831f026-d812-11e5-9106-abebdc454abc.png)

**Comment by tcavaletto** [comment]
![image](https://cloud.githubusercontent.com/assets/5482014/13223523/c5659826-d941-11e5-80e7-340e1e42cc7b.png)

We'll need to have Kreston wrap this (located in  EventItem.lava) in the OSS Ignore div tag, and then Derek can have OSS recrawl the event details pages.

**Comment by tcavaletto** [comment]
Lava is fixed. Problem will resolve as site is recrawled.
