### ISSUE TITLE
Accountability stats are incorrect

### ISSUE THREAD

**Issue by sparkdevnetwork-service** [CentralAZ/Rock-CentralAZ#30]
From Nick - From Jim: For example there are three reports but it shows 2/4:

![image](https://cloud.githubusercontent.com/assets/6056081/13224378/84385b6e-d945-11e5-9b7c-b2bea71490f3.png)

**Comment by tcavaletto** [comment]
![image](https://cloud.githubusercontent.com/assets/5482014/13225510/66b59944-d94a-11e5-8e31-c7a8028ed966.png)
![image](https://cloud.githubusercontent.com/assets/5482014/13225529/82c3ddbc-d94a-11e5-915c-cf4438a41db8.png)

**Comment by tcavaletto** [comment]
For some reason if they've submitted the report for this week another opportunity is added. Researching now.

**Comment by tcavaletto** [comment]
![image](https://cloud.githubusercontent.com/assets/5482014/13225594/c29dc47a-d94a-11e5-940a-44720100ea50.png)
This will also need to change from less than or equal to to less than. It's excluding one of his reports.

**Comment by tcavaletto** [comment]
Fixed in https://github.com/CentralAZ/Rock-CentralAZ/commit/087a7de95dd98263bb7064fc5ec91095b4159949
