### ISSUE TITLE
Score Column of Accountability Report Summary

### ISSUE THREAD

**Issue by nairdo** [CentralAZ/Rock-CentralAZ#32]
The score value in the column is not understood by the users and it confuses them that the % submitted is different than the score in some cases.
![reportsummary](https://cloud.githubusercontent.com/assets/383807/13900519/8a172d78-edc5-11e5-88f9-1e95239b249f.png)

**Comment by tcavaletto** [comment]
Fixed in https://github.com/CentralAZ/Rock-CentralAZ/commit/f5c32522592bff137bce3da2a8e3b5269690c93f
