### ISSUE TITLE
Error updating from v1.4.1 to v1.5

### ISSUE THREAD

**Issue by jeremyhoff** [CentralAZ/Rock-CentralAZ#35]
Howdy,

When updated v1.4.1 to v1.5, (Rock McKinley 5.2) we receive the following error:

Error Updating Database An error occurred while updating the database. 
Error: Cannot insert duplicate key row in object 'dbo.Page' with unique index 'IX_Guid'. The duplicate key value is (6a588baa-9a93-4d4f-9700-2b6ff638296b). Cannot insert duplicate key row in object 'dbo.Block' with unique index 'IX_Guid'. The duplicate key value is (e1a62fa0-ac3b-4ef5-b7b1-b20f1d5aad8c). The statement has been terminated. The statement has been terminated.

Thoughts?
Thanks!

**Comment by tcavaletto** [comment]
@jeremyhoff  Hey, we think you meant to post this on the Spark issues page right here: [Spark Issues Page](https://github.com/SparkDevNetwork/Rock/issues). This page is Central Christian Church's custom stuff :smile: .
