### ISSUE TITLE
Problems with Accountability Statistics

### ISSUE THREAD

**Issue by nairdo** [CentralAZ/Rock-CentralAZ#37]
"I have been inputting my e-accountability report on Friday or Saturday for all of this year, so I should see 100% on my statistics. However, I submitted my report for this last week,
and my stats show that I am credited with 32 out of a possible 28 reports, so I am over 100%. This is not right. Not sure what is causing it, as I do only submit one report for each week. Is there any way you can correct this? Thanks.
Jim"

Use the old code base as a reference because this problem did not exist in my old A***\* module.

**Comment by tcavaletto** [comment]
Credited as 32 because he had 32.  Removed extras. There were a couple reports submitted for the same week. If time allows we should restructure this module.
