### ISSUE TITLE
Lava Tester: Clear Previous Lava or Prevent from Running on Page Load

### ISSUE THREAD

**Issue by briankalwat** [CentralAZ/Rock-CentralAZ#38]
I've got some lava from a previous session that is extremely intensive and it freezes the page – to the point where the plugin is unusable (for my user account). It'd be great if there was a way to keep the plugin from automatically running saved lava (as a preference), or at least have a way to purge previously tested code.

**Comment by jonhorton** [comment]
FWIW, I've run into this same issue a few times.  Would be helpful to remove previous lava, or perhaps a better timeout system that won't prevent the page from loading in the event someone tests bad lava.

**Comment by jonhorton** [comment]
@nairdo Any thoughts on this one?  Have you guys run into this issue on your end?

**Comment by nairdo** [comment]
@jonhorton @briankalwat I looked at this last night and it kept me up thinking about it.  I've got a plan to fix that I'll have time to implement in a few hours.

**Comment by nairdo** [comment]
@jonhorton That fix should resolve the issue you're seeing.  Are you guys comfortable grabbing this latest block code from this commit or are you looking to just upgrade it via the RockShop?  (It will take a few days before I can repackage and reupload a fix for the RockShop.)

**Comment by jonhorton** [comment]
@nairdo We're comfortable pulling the change in, and will test it out with our next release. Thanks so much for the fix—this plugin is so useful!
