### ISSUE TITLE
Spelling error during installer

### ISSUE THREAD

**Issue by smross** [CentralAZ/Rock-CentralAZ#43]
### Description

When installing the package via the Rock Shop there's a spelling mistake:
It says 'suite' when it should say 'suit'
![package install _ rock rms - google chrome 2017-06-22 19 15 04](https://user-images.githubusercontent.com/8688424/27462396-33cb8b40-5786-11e7-964b-506f31ac47d5.png)

### Steps to Reproduce

1. Install the Room Management plugin via the Rock Shop

**Expected behavior:** 

It should say 'suit' instead of 'suite'

### Versions

* **Rock Version:** 6.5, 6.6 Beta 
* **Client Culture Setting** en-us

**Comment by nairdo** [comment]
Thanks! I've corrected that in the plugin package for next time someone installs it.
