### ISSUE TITLE
'New Reservation' block failure

### ISSUE THREAD

**Issue by smross** [CentralAZ/Rock-CentralAZ#44]
### Prerequisites
* [] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?
**Did not do these, as installing the plug-in on the Demo server isn't possible**

### Description

When choosing the `New Reservation` function in the Room Management Plug-In I get an error message:
![new reservation _ rock rms - google chrome 2017-06-22 20 11 01](https://user-images.githubusercontent.com/8688424/27462510-f083a01a-5786-11e7-8d62-adf55038155a.png)

### Steps to Reproduce

1. Install Room Management Plug-in
2. (Optionally) Restart Rock (happens if I restart, or if I don't
3. Go to the Room Management Plug-in 'landing page'
4. Click on the 'New Reservation' Tab

Could this be related to the fact that I had the 'beta' version of this plug-in installed? I'm ready and willing to drop tables, remove files, etc. from my 'beta' server so we can make sure the plug-in works correctly (or whatever you suggest)

**Expected behavior:** 

A page loads walking me through creating a new reservation (with the ReservationDetail block)

**Actual behavior:** 

The error message displays:
`Error Loading Block: Reservation Detail Show Details`
Details:
i:\inetpub\wwwroot\Plugins\com_centralaz\RoomManagement\ReservationDetail.ascx.cs(1487): error CS1501: No overload for method 'IsNullOrWhiteSpace' takes 0 arguments

   at System.Web.Compilation.BuildManager.CompileWebFile(VirtualPath virtualPath)
   at System.Web.Compilation.BuildManager.GetVPathBuildResultInternal(VirtualPath virtualPath, Boolean noBuild, Boolean allowCrossApp, Boolean allowBuildInPrecompile, Boolean throwIfNotFound, Boolean ensureIsUpToDate)
   at System.Web.Compilation.BuildManager.GetVPathBuildResultWithNoAssert(HttpContext context, VirtualPath virtualPath, Boolean noBuild, Boolean allowCrossApp, Boolean allowBuildInPrecompile, Boolean throwIfNotFound, Boolean ensureIsUpToDate)
   at System.Web.UI.TemplateControl.LoadControl(VirtualPath virtualPath)
   at Rock.Web.UI.RockPage.OnInit(EventArgs e)

### Versions

* **Rock Version:** 6.5 & 6.6 Beta
* **Client Culture Setting**   en-us

**Comment by nairdo** [comment]
Drat! I fixed that but must have forgot to repackage it afterwards. I'll get on that right away.

**Comment by nairdo** [comment]
@smross I just re-uploaded the package with this fix.  Since you've already installed, to get this fix you can either remove the entry in your App_Data\InstalledStorePackages.json and then install via the RockShop (this is safe to do in this instance) or you can just download and replace the ReservationDetail.ascx.cs with this one you can manually get from here: https://github.com/CentralAZ/Rock-CentralAZ/blob/central-develop/RockWeb/Plugins/com_centralaz/RoomManagement/ReservationDetail.ascx.cs

**Comment by smross** [comment]
The updated package resolved this error. Thanks
