### ISSUE TITLE
Room Management 'Resources' Categories oddity

### ISSUE THREAD

**Issue by smross** [CentralAZ/Rock-CentralAZ#45]
### Prerequisites
**I did not do this, as installing this plug-in on the demo server isn't doable**
* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

After installing the Room Management Plug-in from the Rock Shop, some of the created resources have odd 'categories' linked

### Steps to Reproduce

1. Install the Room Management Plug-in
2. Go to the `Room Management` landing page (Intranet -> Office Information -> Room Management)
3. Select the `Admin Tools` tab
4. Select the `Resources` icon (for the `Resources` page)

**Expected behavior:** 

Resources use categories that are relevant to Room Management

**Actual behavior:** 

The 'stock' Resources have odd linkages to categories:
The resource `Van 14` is listed under the Category `Link Lists`
The resource `Baptism tub` is listed under the Category `Plugins`
The resource `Lobby Tables` is listed under the Category `Family Analytics`
The resource `Children's Portable Projector` is listed under the Category `Registration`
The resource `Gym Chairs` is listed under the Category `Person Analytics`

This makes no sense to me...
![resources _ rock rms - google chrome 2017-06-22 20 20 12](https://user-images.githubusercontent.com/8688424/27462833-16e62e2e-5789-11e7-97c3-3ed39abe3d19.png)

### Versions

* **Rock Version:** 6.5 and 6.6 Beta
* **Client Culture Setting** en-US

**Comment by tcavaletto** [comment]
Shawn,
 We had this issue with earlier versions of the plugin but then fixed it in this commit:
https://github.com/CentralAZ/Rock-CentralAZ/commit/f1f5e6074d3cea6c8238587dae09d401252c9d8e

Did you install this on a fresh Rock instance or on top of an instance with older Room Management code?

**Comment by smross** [comment]
Taylor, I have not installed the plugin on a 'fresh' instance of Rock yet. The 2 instances I have available at the moment both had the 'beta' room management code. However, I _did_ do some kind of uninstall/reset under Nick's direction as part of #44 :
> Since you've already installed, to get this fix you can either remove the entry in your App_Data\InstalledStorePackages.json and then install via the RockShop (this is safe to do in this instance) or you can just download and replace the ReservationDetail.ascx.cs with this one you can manually get from here: https://github.com/CentralAZ/Rock-CentralAZ/blob/central-develop/RockWeb/Plugins/com_centralaz/RoomManagement/ReservationDetail.ascx.cs

At the time I was concerned that my 'upgrading' could cause issues, so I took Nick's directions while trying to 'remove' any 'beta plugin' code:
* Removed the entry in the App_Data\InstalledStorePackages.json
* Removed the file 'com.centralaz.RoomManagement.dll' from inetpub\wwwroot\Bin
* Removed the folder 'RoomManagement' from inetpub\wwwroot\Plugins\com_centralaz (I also have LavaTester installed)
* Restarted Rock
* Ran the 'install' process from the Rock Shop again
* Restarted Rock

If you'd like me to 'completely' uninstall any version of the plugin code, I'm game for that. I'm just not sure what to do beyond what's listed above

**Comment by tcavaletto** [comment]
It sounds like you deleted the old code, which is good, but the 'fixed' migration that added the resources and categories was marked as already run on your database, so it wasn't run again. As far as fixing the categories, manually updating them would be the easiest thing to do.

**Comment by smross** [comment]
OK. Great. That works for me!

Is there a way to 'reset' my config to not have any room management info?
If it's complicated SQL, etc. don't worry about it, but I thought I would
ask if there was an easy way


Shawn Ross
IT Specialist
Calvary Church
sross@calvaryonline.cc
636-939-4343 x1136
http://www.calvaryonline.cc
