### ISSUE TITLE
[RR] Setup Thumbnails broken

### ISSUE THREAD

**Issue by smross** [CentralAZ/Rock-CentralAZ#46]
### Prerequisites
**I did not do prerequisites on the Demo site; no way to install this plugin there**
* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

When attaching a PDF or JPG to a reservation (under the setup section), the 'thumbnail' for the setup shows a broken image placeholder
![room management _ rock rms - google chrome 2017-06-22 20 59 49](https://user-images.githubusercontent.com/8688424/27463521-c7fe1c72-578d-11e7-82df-b4963b7b027c.png)

### Steps to Reproduce

1. Edit a reservation
2. Select the "Setup Photo" `Upload` button
3. Specify a file (I tried PDF and JPG)
4. Save the reservation
5. Find the reservation in a list/grid

**Expected behavior:** 

A thumbnail shows a preview of the file and it's clickable for the full version

**Actual behavior:** 

I get a 'broken image' image on the "Room Management" landing page
![room management _ rock rms - google chrome 2017-06-22 21 17 16](https://user-images.githubusercontent.com/8688424/27463963-48fe089e-5790-11e7-9837-d9e3bd6419ef.png)
_The link in my picture is to <rock server>/page/~GetImage.ashx?id=306_

If I click on the (broken) thumbnail I get an error page
![rock - page not found - google chrome 2017-06-22 21 18 21](https://user-images.githubusercontent.com/8688424/27463971-5712f16a-5790-11e7-91aa-01c941e6c412.png)

### Versions

* **Rock Version:** 6.5, 6.6 Beta
* **Client Culture Setting** en-US

**Comment by smross** [comment]
@tcavaletto the two modified files, "ReservationLava.ascx.cs" and "Reservation.lava" resolved the issue. The linked uploads/attachments both now render on the 'grid' and display when you click them

**Comment by nairdo** [comment]
@tcavaletto fixed this via 3f82e59.
