### ISSUE TITLE
[RR] Statuses invisible in Reservation Configuration

### ISSUE THREAD

**Issue by smross** [CentralAZ/Rock-CentralAZ#47]
### Prerequisites
**I did not do prerequisites on the Demo site; no way to install this plugin there**
* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

The `Reservation Configuration` page does not include `statuses` as the documentation says it should, even if I'm logged in as a Rock Administrator and Room Administrator

### Steps to Reproduce

1. Login to the Room Management landing page
2. Select the `Admin Tools` tab
3. Select the `Reservation Configuration` tab

**Expected behavior:** 

You receive a listing of the configurable options, including Ministries, Status, Workflow Triggers

**Actual behavior:** 

I receive the options for `Ministries` and `Workflow Triggers` but not `Statuses`
![reservation configuration _ rock rms - google chrome 2017-06-22 21 33 09](https://user-images.githubusercontent.com/8688424/27464325-6a03fdc6-5792-11e7-82ba-2c949c81ba28.png)

### Versions

* **Rock Version:** 6.5 & 6.6 Beta
* **Client Culture Setting** en-US

**Comment by nairdo** [comment]
Thanks Ross. I'll have Taylor update the documentation and remove that section.  The way statuses and approvals is handled is quite a bit different from the early alpha versions.

**Comment by tcavaletto** [comment]
Documentation updated.
