### ISSUE TITLE
[RR] Printed Report has Central Christian Logo

### ISSUE THREAD

**Issue by sbehrendsohc** [CentralAZ/Rock-CentralAZ#59]
### Prerequisites
* [ x] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

When you print the Room Management report, it shows the Central Christian logo in the PDF

### Steps to Reproduce

1. Dive into Room Management
2. Hit print
3. The downloaded PDF has the CC logo

**Expected behavior:** 

Have our own logo there. 
Have a place to be able to change the logo. 
Document location for us to change it.

**Actual behavior:** 

Not exactly sure where the logo file is since the PDF is generated. Will have to track it down.

### Versions

* **Rock Version:** Rock McKinley 6.9  
* **Client Culture Setting:** en-US

**Comment by nairdo** [comment]
I believe you're referring to the logo that is pulled in from the block's settings:

![image](https://user-images.githubusercontent.com/383807/32907822-ac5b6052-cabe-11e7-823d-722e5053faea.png)

Feel free to update that setting as needed.
