### ISSUE TITLE
RR: Room Reservation Report enhancements

### ISSUE THREAD

**Issue by eddieholeman** [CentralAZ/Rock-CentralAZ#61]
### Prerequisites
* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

Below are 2 enhancement suggestions:

1. Our facilities team will use the room reservation report on paper as they move throughout the buildings setting up rooms for events.  Being able to include Ministry and Contact Info in this report would be valuable to them.  I have not been able to find a manner of doing that.  

2. Why this report is setup with PageSize.A4?  We don't normally use A4, but Letter doesn't seem to be an available property.  The only problem this presents is top and bottom margins.  Would also like a landscape option on that report as well as better pagebreak.

### Steps to Reproduce
 Go to Room Management and click the Print link.

### Versions

* **Rock Version:** Rock Version 6.9 (Sandbox version 6.10) 
                              Room Management version 1.2.0
* **Client Culture Setting:** [Enter Client Culture here]

**Comment by tcavaletto** [comment]
@eddieholeman  The next release will include Report Templates that you can select between to determine what your printed report would look like. Included in these will one in landscape mode with ministry and contact info.
