### ISSUE TITLE
[RR] Final Approval Group Security Role Requirement

### ISSUE THREAD

**Issue by smross** [CentralAZ/Rock-CentralAZ#62]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

When specifying a "Final Approval Group", only groups that are Security Roles work.

### Steps to Reproduce

1. Create a group and add members. I used a group of type Organizational Unit
2. Open the Block Properties for a New Reservation page
3. Select the drop-down for 'Final Approval Group'

**Expected behavior:** 

I expect to be able to choose a group besides just security roles
![new reservation _ rock rms - google chrome 2017-12-14 13 27 30](https://user-images.githubusercontent.com/8688424/34010878-ca0efd86-e0d3-11e7-8747-a1bc909b02ca.png)

**Actual behavior:** 

I tried to work around this:
1. Set my organizational unit group to have 'security role' enabled
2. Changed the block settings to use my group as the final approval group (it shows up in the drop-down)
3. Set my organizational unit group to no long have 'security role' enabled
4. I force refreshed the page with the new reservation block, and there was no longer a Final Approval Group set

### Versions

* **Rock Version:**  6.9 
* **Client Culture Setting:** en-US

**Comment by tcavaletto** [comment]
Shawn,
This is working as built. We have it set to only use security roles because the Final Approval Group serves the same purpose as a security role does, and to reduce clutter in the dropdown to select it.

**Comment by nairdo** [comment]
Of course you can just click the 'is security role' option on the group your looking to use and then it will show up in the list.

Taylor and I will discuss renaming this field (and documentation) to "Final Approval Role" to avoid future confusion.

**Comment by smross** [comment]
Thanks @tcavaletto and @nairdo 

That's good to understand. I also appreciate the consideration of a clarification. That would help with expectations as I would then assume the group must be a security role
