### ISSUE TITLE
RR: The Lava command 'execute' is not configured for this template, error.

### ISSUE THREAD

**Issue by LindaHawker** [CentralAZ/Rock-CentralAZ#64]
### Prerequisites
* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

We have followed the instructions for the set up and I have set the lava command to execute but the confirmation email still says "The Lava command 'execute' is not configured for this template."
Can you tell me what we need to do to correct this, or what we have done wrong.

### Steps to Reproduce

1. Room Reservation
2. Approval
3. Email confirmation received with error.

**Expected behavior:** 

1. Room Reservation
2. Approval
3. Email confirmation received with no error's.

**Actual behavior:** 

1. Room Reservation
2. Approval
3. Email confirmation received with error.
![screen shot 2018-01-02 at 2 46 31 pm](https://user-images.githubusercontent.com/35020073/34474583-8e957714-efcc-11e7-82de-66b82851dd13.png)
![screen shot 2018-01-02 at 2 46 00 pm](https://user-images.githubusercontent.com/35020073/34474588-9eab4bba-efcc-11e7-9be7-ca0944cfd398.png)

### Versions

* **Rock Version:** [6.10]  
* **Client Culture Setting:** [en-USA]

**Comment by nairdo** [comment]
@LindaHawker can you include a screenshot of your Global Attributes list that shows the Default Enabled Lava Commands? Like this:
![image](https://user-images.githubusercontent.com/383807/34490286-a89458ae-ef9c-11e7-86df-4482cd8290d9.png)

The screenshot you attached indicates you've set the attribute _default settings_ -- but not the attribute values.  For that you'd need to click the entire row -- not the edit/pencil button.  When you set the attribute value it will look like this:

![image](https://user-images.githubusercontent.com/383807/34493321-93c84550-efa8-11e7-96ac-4739d25b8a8f.png)

**Comment by LindaHawker** [comment]
This is what it looks like


Linda Hawker

Grace Church
Office Manager

lindah@gracefoursquare.org
Ph. 360 834 6336

**Comment by LindaHawker** [comment]
I have changed our values to match yours and it works thank you so much.
Linda Hawker

Grace Church
Office Manager

lindah@gracefoursquare.org
Ph. 360 834 6336

**Comment by LindaHawker** [comment]
Hi I’m not sure if you can help me or not, hopefully yes though.

I was wondering if you have documentation for the workflows for room reservation approvals with an approval group.

I was hoping you may have a list of all the actions involved in each part required.

We can’t seem to get the workflows to work, and don’t know why.

Linda Hawker

Grace Church
lindah@gracefoursquare.org
Ph. 360 834 6336

**Comment by nairdo** [comment]
@tcavaletto might be able to comment on this better than me (and I'll have limited access for the next few days) but if I'm not mistaken, Taylor said approval notifications (using a system email template) are sent immediately upon saving the Reservation when location/resource based approval groups are involved, and the approval notification *workflow* is only used when a super approval group has been configured in the block setting.

Taylor is this correct?

**Comment by tcavaletto** [comment]
That's correct. @LindaHawker , what part do you seem to be struggling with? What does the workflow look like on your system?

**Comment by LindaHawker** [comment]
Hi Taylor
Sorry for taking so long to get back to you.
We want to have the room reservation approved with an approval group.
We have been trying to set this up, and have reloaded the plug in now twice but we still can’t figure out what we are doing wrong.
I need to be able to approve the reservation. We have RSR Room Management Administration which I am on.
I haven’t touched any of the workflows but I didn’t reinstall the plug in, our other administrator did that. I at the moment don’t get emails alerting me to new room reservations and if I go in and approve them they are always staying at the pending review state.
So I figure its the workflow.
I have attached the screen shots of the workflow trigger.
Hopefully you can tell me how to fix it.

Linda Hawker

Grace Church
lindah@gracefoursquare.org
Ph. 360 834 6336
