### ISSUE TITLE
[RR] Lack of date info in error msg when trying to reserve a room that is already reserved

### ISSUE THREAD

**Issue by edcylam** [CentralAZ/Rock-CentralAZ#66]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

When a new reservation is attempting to reserve a room for multiple dates and one of the dates has the room already reserved, the error message doesn't specify the double booked date. 

### Steps to Reproduce

1.  Create the first reservation for the event "Alpha" with a location and a single date schedule (e.g. Room 217 for 4/7/18 Saturday at 5pm).
2. Create a second reservation for the event "Beta" with the same location and a schedule with multiple dates (e.g. Room 217 for 4/7/18 Saturday at 5pm and continue every Saturday until 4/28/18.

**Expected behavior:** 

The expected error message should say: 

The following items are already reserved for the schedule times: 
* Room 217 due to:
   * Room 217 [on 4/7/18 Saturday at 5:00 PM via 'Alpha']

**Actual behavior:** 

The current error message says: 

The following items are already reserved for the schedule times: 
* Room 217 due to:
   * Room 217 [on Saturday at 5:00 PM via 'Alpha'] (Doesn't specify the date)

### Versions

* **Rock Version:** 7.3 
* **Client Culture Setting:** en-US

**Comment by nairdo** [comment]
Unfortunately the schedule's 'friendly name' is controlled by Rock core code.  If I set up a reservation schedule with two dates and then try to set up a conflicting reservation, the conflict's message looks like this:

![image](https://user-images.githubusercontent.com/383807/39020971-a8121376-43e3-11e8-906c-583530a4ccbe.png)

...but schedules with a weekly occurrence pattern will not show the date in the [FriendlyScheduleText code](https://github.com/SparkDevNetwork/Rock/blob/develop/Rock/Model/Schedule.cs#L607).

**Comment by edcylam** [comment]
Ok...I have a quick, separate question. In the "Your Reservation has been
Approved" message, I receive the following 2 Liquid errors. Any idea?

Your reservation has been approved:

Name: Omega
Requestor: Edmund Lam
Campus:
Ministry:
Number Attending: 30

Schedule: Liquid error: Object reference not set to an instance of an
object.
Event Duration: Liquid error: Object reference not set to an instance of an
object.
Setup Time: 30 min
Cleanup Time: 30 min
Locations: Room 217





<http://www.venturechristian.org/>
*Edmund*Lam
PROJECT MANAGER - LIFE GROUPS
edmund@venture.cc | 408.997.4691 <(408)%20997-4691>
*16845 Hicks Road, Los Gatos, CA 95032
<https://www.google.com/maps/place/16845+Hicks+Rd,+Los+Gatos,+CA+95032/data=!4m2!3m1!1s0x808e36b3fcbbf1c9:0x1d7da23ee96c622?sa=X&ved=0ahUKEwjwtMDK-qrOAhUMwmMKHW8vDNIQ8gEIHDAA>*

**Comment by nairdo** [comment]
We were able to pin-point that "Liquid error" issue to a [bug in Rock v7 ](https://github.com/SparkDevNetwork/Rock/issues/2904 )which has been addressed in [this v7.4 fix](https://github.com/SparkDevNetwork/Rock/commit/e431d37626dea42cd984889d8195479c154d7378).
