### ISSUE TITLE
[RR] Unable to Load Location List in New Reservation

### ISSUE THREAD

**Issue by edcylam** [CentralAZ/Rock-CentralAZ#67]
### Prerequisites
* [ x] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

When a new reservation is being created and a new location is being added, the location list displays "Error" in red.

### Steps to Reproduce

1.  Click New Reservation.
2. Fill out Event Name and Schedule
3. Go to Locations and click the "+" sign
4. Click the down arrorw in Locations
5. "Error" is displayed in red

Note: This is a fresh Rock install.

**Expected behavior:** 

The list of the locations should be listed for choosing.

**Actual behavior:** 

The list is empty, and "Error" is displayed in red. The location list is shown properly in Admin > Check-in > Check-in Configurations > Check-in Group

### Versions

* **Rock Version:** 7.3  
* **Client Culture Setting:** en-US

**Comment by nairdo** [comment]
This was caused by a problem with the REST endpoints on the system in question.  @edcylam did you and KFS ever figure out why your REST endpoints were not being registered?

**Comment by edcylam** [comment]
David Stevens of KFS fixed the issue, but I forgot the details.
