### ISSUE TITLE
[RR] Liquid error in Approval Email

### ISSUE THREAD

**Issue by tommyprater** [CentralAZ/Rock-CentralAZ#71]
Before completing your first issue we highly recommend reading this post on [Effective Ways To Get Help from Maintainers](https://www.snoyman.com/blog/2017/10/effective-ways-help-from-maintainers).

### Prerequisites
* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

In the emails that go to the approvers in the line for "Event Duration:" I get this error: Object reference not set to an instance of an object.

I did make sure that I have the value Execute checked for Default Enabled Lava Commands.

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** 

[What you expected to happen]

**Actual behavior:** 

[What actually happened]

### Versions

* **Rock Version:** [7.3]  
* **Client Culture Setting:** [1.0.1]

**Comment by nairdo** [comment]
This is an issue (Sparkdevnetwork/Rock#2904) with Rock core.  It's being addressed in Rock v7.4.
