### ISSUE TITLE
[RR] Date Range filter not auto refreshing/confusing

### ISSUE THREAD

**Issue by mkinyon** [CentralAZ/Rock-CentralAZ#72]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

Changing the date range filter doesn't auto update the results like the other options do... such as "Filter by Approval State".  It's possible that the Refresh button is required to filter by dates but it's not exactly clear by looking at the UI.  Thanks for taking a look at this.

![image](https://user-images.githubusercontent.com/2349102/41240384-3ad77428-6d4f-11e8-97cf-e1be2a84f197.png)

### Steps to Reproduce

1. Change the date range.

**Expected behavior:** 

Expected the results to dynamically update.

**Comment by tcavaletto** [comment]
Added in https://github.com/CentralAZ/Rock-CentralAZ/commit/913965ac9ffb40a97a42a8f4cc1198932954b005
