### ISSUE TITLE
[RR] Enhancement - Reserve multiple rooms (locations) at the same time

### ISSUE THREAD

**Issue by mkinyon** [CentralAZ/Rock-CentralAZ#74]
_Submitting this on behalf of The Village Church._

### Description
When reserving many rooms for a reservation, the staff member has to reserve each room one at a time.  We're hoping that the interface can be updated to make this experience faster.  
![image](https://user-images.githubusercontent.com/2349102/41559360-acdea5d8-72f8-11e8-98cd-4bb0ee0a045c.png)

**Comment by tcavaletto** [comment]
'Save then Add' feature added to the ReservationResource and ReservationLocation modals with commithttps://github.com/CentralAZ/Rock-CentralAZ/commit/611f01c25e6c2247a7da863d3d235c844886a964

**Comment by timlem** [comment]
Will these be in 1.3?
