### ISSUE TITLE
[RR] Enhancement - "Select All" option to approve all locations/resources at once

### ISSUE THREAD

**Issue by mkinyon** [CentralAZ/Rock-CentralAZ#75]
_Submitting on behalf of The Village Church_

### Description
Looking to have a a button added to the reservation detail that will allow an approver to approve all locations or resources at the same time.  This could be helpful with reservations that have a lot of locations/resources.
![image](https://user-images.githubusercontent.com/2349102/41560405-cb36a884-72fb-11e8-9b2d-587c42b1dfc8.png)

**Comment by tcavaletto** [comment]
Added in https://github.com/CentralAZ/Rock-CentralAZ/commit/611f01c25e6c2247a7da863d3d235c844886a964#diff-b8d265400f417e3012837afb0df4e693
