### ISSUE TITLE
[RR] Enhancement - Include "End On" Option to Schedule for Recurring Events

### ISSUE THREAD

**Issue by edcylam** [CentralAZ/Rock-CentralAZ#78]
### Description

The "End By" creates some confusion for me and my team when we are setting up a reservation for a recurring event. Some people would think it includes the last event day while others think it doesn't include it although the correct interpretation is the latter. Also, it is inconsistent with how other popular calendaring applications, such as Google Calendar, work (they use "Ends On") for scheduling recurring events. As a result, people can easily make a mistake to miss out the last event day in the plug-in.

Here are my suggestions of how to solve the issue while making sure compatibility with existing users who are used to "End By" in the plug-in:

- Offer a toggle option between “Ends By” and “Ends On” in a Reservation Detail block with “Ends By” as the default setting. When it switches from one setting to the other, the code can automatically update the date (i.e. +/- 1 day). Then, it would not impact existing users while pleasing new users like me. :) 
- Include an occurrence preview like the one in General Settings > Schedules so that users can confirm they included the correct dates & times. There is some limited preview info under Schedule in New Reservation today, but it is insufficient for recurring events.

### Versions

* **Rock Version:** 7.4
* **Client Culture Setting:** en-US

**Comment by nairdo** [comment]
Thanks for sharing this idea with us.  The End By piece of a schedule is actually just core functionality from Rock and not something we control in this plugin.

**Comment by edcylam** [comment]
Can we bring up this option to Rock/Spark's team?

<http://www.venturechristian.org/>
*Edmund*Lam
PROJECT MANAGER - LIFE GROUPS
edmund@venture.cc | 408.997.4691 <(408)%20997-4691>
*16845 Hicks Road, Los Gatos, CA 95032
<https://www.google.com/maps/place/16845+Hicks+Rd,+Los+Gatos,+CA+95032/data=!4m2!3m1!1s0x808e36b3fcbbf1c9:0x1d7da23ee96c622?sa=X&ved=0ahUKEwjwtMDK-qrOAhUMwmMKHW8vDNIQ8gEIHDAA>*
