### ISSUE TITLE
Room Management Event Approved Email Bug

### ISSUE THREAD

**Issue by tbunney** [CentralAZ/Rock-CentralAZ#79]
Before completing your first issue we highly recommend reading this post on [Effective Ways To Get Help from Maintainers](https://www.snoyman.com/blog/2017/10/effective-ways-help-from-maintainers).

### Prerequisites
* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

We upgraded to v7.4, and some of the notifications for Rock Room Management are fixed, but I now we are getting a different error in the approval notification. I tried to copy and paste from the email that was fixed, but it still does not work. Do you have any suggestions? The screenshot of the email is attached.
![roommanagementapproval](https://user-images.githubusercontent.com/37702418/42326957-983b0f3e-8038-11e8-89d8-bc07a3df0f41.PNG)

The current lava in the email is:
 Schedule: {% execute import:'com.centralaz.RoomManagement.Model'%} 
var reservation = new ReservationService( new RockContext()).Get({{Reservation.Id}});
return reservation.Schedule.FriendlyScheduleText;
{% endexecute %}<br/>
Event Duration: {% execute import:'com.centralaz.RoomManagement.Model'%} 
var reservation = new ReservationService( new RockContext() ).Get({{Reservation.Id}});
return reservation.Schedule.GetCalenderEvent().Duration.Hours + " hrs " + reservation.Schedule.GetCalenderEvent().Duration.Minutes + " min";
{% endexecute %}<br/>

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** 

[What you expected to happen]

**Actual behavior:** 

[What actually happened]

### Versions

* **Rock Version:** [Enter Rock version here]  
* **Client Culture Setting:** [Enter Client Culture here]

**Comment by tcavaletto** [comment]
@tbunney  if you edit the lava on the lines with `var reservation = new ReservationService( new RockContext()).Get({{Reservation.Id}});` to `var reservation = new ReservationService( new RockContext()).Get({{reservation.Id}});`, does that solve your problem?

**Comment by nairdo** [comment]
The original, complete email content for that "Notify Requester that the Reservation has been Approved" activity should look like this:

```csharp
{{ 'Global' | Attribute:'EmailHeader' }}
{% assign reservation = Workflow | Attribute:'Reservation','Object' %} 
<p>
Your reservation has been approved:<br/><br/>
Name: {{ reservation.Name }}<br/>
Requestor: {{ reservation.RequesterAlias.Person.FullName }}<br/>
Campus: {{ reservation.Campus.Name }}<br/>
Ministry: {{ reservation.ReservationMinistry.Name }}<br/>
Number Attending: {{ reservation.NumberAttending }}<br/>
<br/>
Schedule: {% execute import:'com.centralaz.RoomManagement.Model'%} 
    var reservation = new ReservationService( new RockContext()).Get({{reservation.Id}});
    return reservation.Schedule.FriendlyScheduleText;
{% endexecute %}<br/>
Event Duration: {% execute import:'com.centralaz.RoomManagement.Model'%} 
    var reservation = new ReservationService( new RockContext()).Get({{reservation.Id}});
    return reservation.Schedule.GetCalenderEvent().Duration.Hours + " hrs " + reservation.Schedule.GetCalenderEvent().Duration.Minutes + " min";
{% endexecute %}<br/>
Setup Time: {{ reservation.SetupTime }} min<br/>
Cleanup Time: {{ reservation.CleanupTime }} min<br/>
{% assign locationSize = reservation.ReservationLocations | Size %}{% if locationSize > 0 %}Locations: {% assign firstLocation = reservation.ReservationLocations | First %}{% for location in reservation.ReservationLocations %}{% if location.Id != firstLocation.Id %}, {% endif %}{{location.Location.Name }}{% endfor %}<br/>{% endif %}
{% assign resourceSize = reservation.ReservationResources | Size %}{% if resourceSize > 0 %}Resources: {% assign firstResource = reservation.ReservationResources | First %}{% for resource in reservation.ReservationResources %}{% if resource.Id != firstResource.Id %}, {% endif %}{{resource.Resource.Name }} ({{resource.Quantity}}){% endfor %}<br/>{% endif %}
<br/>
Notes: {{ reservation.Note }}<br/>
<br/>
<a href='{{ 'Global' | Attribute:'InternalApplicationRoot' }}reservationdetail?ReservationId={{reservation.Id}}'>View Registration</a>
</p>
{{ 'Global' | Attribute:'EmailFooter' }}
```

**Comment by tbunney** [comment]
Thanks! This is working now.
