### ISSUE TITLE
[RR] Inactive Rock location (room) shows up on Room Management Available Resources page. 

### ISSUE THREAD

**Issue by sanford-rock** [CentralAZ/Rock-CentralAZ#80]
Before completing your first issue we highly recommend reading this post on [Effective Ways To Get Help from Maintainers](https://www.snoyman.com/blog/2017/10/effective-ways-help-from-maintainers).

<[RR] Inactive Rock location (room) shows up on Room Management Available Resources page. I don't think this location should be available. Also is there is a way to exclude locations from this page in addition to the filters?>

### Prerequisites
* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

[[RR] Inactive Rock location (room) shows up on Room Management Available Resources page. I don't think this location should be available. Also is there is a way to exclude locations from this page in addition to the filters?]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** 

[I don't expect to see Inactive Locations show up as being available]

**Actual behavior:** 

[Inactive Locations show up as Available]

### Versions

* **Rock Version:** [7.3]  
* **Client Culture Setting:** [What is Client Culture Settings?]

**Comment by tcavaletto** [comment]
Fixed in v1.3
