### ISSUE TITLE
"Central Christian Church" Logo on Reservations Printout

### ISSUE THREAD

**Issue by edcylam** [CentralAZ/Rock-CentralAZ#82]
### Description

In the reservations printout PDF, it has the Central Chistian Church logo. It would be ideal if there is an option to allow users to replace with their church logos.

![screen shot 2018-07-19 at 2 49 49 pm](https://user-images.githubusercontent.com/24534451/42972764-7306ea52-8b65-11e8-88f6-e66717a9d722.png)

### Versions

* **Rock Version:** 7.4
* **Client Culture Setting:** en-us

**Comment by nairdo** [comment]
There is a block setting for changing the logo called "Report Logo".
