### ISSUE TITLE
Existing Reservations Editable by Any Users

### ISSUE THREAD

**Issue by edcylam** [CentralAZ/Rock-CentralAZ#83]
### Description

It seems that all users, not just the approvers, can go to edit any reservations (see screenshot attached). The only thing that regular users cannot do is to change the locations and resources. I think reservations should only be allowed to be altered by their requestors and approvers. Is it by design or an issue? 
 
![screen shot 2018-07-19 at 2 49 25 pm](https://user-images.githubusercontent.com/24534451/42972932-08844d5e-8b66-11e8-96af-30cc7750892d.png)

### Versions

* **Rock Version:** 7.4
* **Client Culture Setting:** en-us

**Comment by nairdo** [comment]
This is by design.
