### ISSUE TITLE
Display issue in the Room Reservation Configuration Workflow Triggers Tab

### ISSUE THREAD

**Issue by TheCoreyHall** [CentralAZ/Rock-CentralAZ#84]
Before completing your first issue we highly recommend reading this post on [Effective Ways To Get Help from Maintainers](https://www.snoyman.com/blog/2017/10/effective-ways-help-from-maintainers).

### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

If an admin creates a State Changed Workflow Trigger for Room Reservation and fills in the "From" and "To" conditions for the trigger and saves it, when they refresh the page again and open the trigger, the "From" and "To" fields will be empty. However this is only one the first time opening the trigger after refreshing. If the fields are empty on opening, closing the trigger and opening it again will display the fields

### Steps to Reproduce

1. Go to Workflow Triggers in Room Configuration
2. Create a New "State Changed" Trigger and fill in the workflow type, "To" and "From" fields
3. Save the trigger and refresh the page
4. Open the newly created trigger and the "To" and "From" fields will be empty

**Expected behavior:** 

The "To" and "From Fields will display their values when opening for the first time.

**Actual behavior:** 

The fields are empty after opening on first visit, then filled in when viewing it again without refreshing

### Versions

* **Rock Version:** [7.4]  
* **Client Culture Setting:** [en-us]  ("en-us", "en-gb", etc.)  <a href="https://www.rockrms.com/github-detect-client-culture-setting" target="_blank">unsure? detect what yours is here (right click and open in new window)</a>

**Comment by tcavaletto** [comment]
Fixed in 1.3.0
