### ISSUE TITLE
Add Note Block to New Reservation page Section A

### ISSUE THREAD

**Issue by sanford-rock** [CentralAZ/Rock-CentralAZ#85]
### Prerequisites
* [x ] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

We need to have a Event Description field (note block) available on the New Reservation page in addition to the Note field currently available. I tried adding a Note zone to Section A but it seems the only thing you can add that is visible is just an HTML zone with text. Should I be able to do this since I'm outside of the page code? 

thanks,

Current Rock Version 7.3
 Client Culture "en-us"

**Comment by nairdo** [comment]
Hi @sanford-rock, if you create a new 'note type' and add the standard Rock "Notes" block to the Reservation Detail page and configure it similar to the way I described [adding a Notes block to your Workflow Configuration page in this blog post](https://shouldertheboulder.com/article/adding-a-change-log-to-workflow-configurations) it should work for you.

I just tried on my test system and it worked. Here are some screenshots from that setup:

![image](https://user-images.githubusercontent.com/383807/55662303-e0502280-57c6-11e9-9681-4b801dce772c.png)

![image](https://user-images.githubusercontent.com/383807/55662305-e34b1300-57c6-11e9-9bc0-8e686f0746c7.png)

![image](https://user-images.githubusercontent.com/383807/55662310-e6de9a00-57c6-11e9-9805-c1319f0f2d00.png)
