### ISSUE TITLE
Hide "Inactive" Locations from Picker and Filter

### ISSUE THREAD

**Issue by nairdo** [CentralAZ/Rock-CentralAZ#86]
### Prerequisites
* [x ] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

Currently inactive campus/locations are showing up in Location pickers and the filters.

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** 

They should be hidden unless on an existing reservation.

**Actual behavior:** 

### Versions

* **Rock Version:** 7.5
* **Room Management Version:** 1.3.0

**Comment by tcavaletto** [comment]
Fixed in https://github.com/CentralAZ/Rock-CentralAZ/commit/6627174638d77fcfce043353fcb4bcabf510afde
