### ISSUE TITLE
Reservation Question

### ISSUE THREAD

**Issue by sanford-rock** [CentralAZ/Rock-CentralAZ#87]
Before completing your first issue we highly recommend reading this post on [Effective Ways To Get Help from Maintainers](https://www.snoyman.com/blog/2017/10/effective-ways-help-from-maintainers).

### Prerequisites
* [ x] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

Hi all, I have a question regarding the Room Mgt. plug-in we recently purchased and installed...on the Location or Resources you can add a Reservation question for that Location or Resource...you can also copy that question to a new Location or Resource...what I need to know is if anyone has a SQL script where I can copy the question to all of the Locations that are setup for Room Mgt. Can anyone help or give me an idea on this request?  thanks...

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** 

[We want to use the question to capture an Event Description for each reservation that is created.]

**Actual behavior:** 

[the Reservation Question works we just need it for all reservations and assume if the same question is assigned to all locations this will accomplish what we need.]

### Versions

* **Rock Version:** [v7.3]  
* **Client Culture Setting:** [Enter Client Culture here]  ("en-us", "en-gb", etc.)  <a href="https://www.rockrms.com/github-detect-client-culture-setting" target="_blank">unsure? detect what yours is here (right click and open in new window)</a>

**Comment by nairdo** [comment]
No, the only feature that exists is the "Copy Questions From..." that will let you copy a set of questions to a location/resource _from_ an existing location/resource.

I would recommend you use the reservation note field for that purpose. (If you successfully put those questions on all locations, then if you included multiple locations in a reservation, a person would have to answer the same question multiple times -- one time for each location.)

**Comment by sanford-rock** [comment]
Hey Nick thanks for the reply in that there is not a ‘bulk update’ process to copy the question to all locations…I’ve got another question  about room mgt...I created a new reservation with a room that's in one location and added a resource that is attached to another location...I thought assigning an Attached Location to a resource would keep that from being used in a different location...is this a bug? Also Jason Gibb said that we could create a Reservation entity attribute for a ‘description’, did that, but how is it supposed to show up on the New Reservation page?... thanks...Richard

**Comment by nairdo** [comment]
No, attaching a resource to a location only causes that resource to be added (initially) when a new reservation is created with that location.  The user can still remove it (if they don't want it) or they can include that resource in another reservation if it's available.
