### ISSUE TITLE
RR - Can

### ISSUE THREAD

**Issue by jrockman13** [CentralAZ/Rock-CentralAZ#90]
### Prerequisites
* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

This issue is still occurring after 1.3.1 update: [https://github.com/CentralAZ/Rock-CentralAZ/issues/81}

### Steps to Reproduce

See issue 81

### Versions

* **Rock Version:** 8.3
* **Client Culture Setting:** en-us

**Comment by nairdo** [comment]
Re-opened #81.
