### ISSUE TITLE
[RR] multiple occurrences are not showing the scheduled dates when viewing the event details

### ISSUE THREAD

**Issue by nairdo** [CentralAZ/Rock-CentralAZ#92]
### Prerequisites
* [ X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

**From:** Sonia Kuppinger <Sonia.Kuppinger@CentralAZ.com>

Starting in January 2019, reservations that have multiple occurrences are not showing the scheduled dates when viewing the event details. Let me show you:
This event shows all the dates…this way approvers know when the event is happening, this is the initial view:
![1](https://user-images.githubusercontent.com/383807/46441703-3363f280-c71c-11e8-8565-499612242beb.png)

This is when you click on the reservation:
![2](https://user-images.githubusercontent.com/383807/46441708-365ee300-c71c-11e8-97ce-2ad6a4c89d9b.png)

But this one in January…and pretty much all of them look like this:

![3](https://user-images.githubusercontent.com/383807/46441716-3959d380-c71c-11e8-8688-581c90ec1bba.png)

![4](https://user-images.githubusercontent.com/383807/46441748-4c6ca380-c71c-11e8-8def-d4b4452d0626.png)

And they did set up their calendar correctly:

![5](https://user-images.githubusercontent.com/383807/46441803-7625ca80-c71c-11e8-80f7-3a4124253532.png)

### Versions

* **Rock Version:** Rock v1.8.3 with Room Management v1.3.1.0

**Comment by tcavaletto** [comment]
![image](https://user-images.githubusercontent.com/5482014/77675795-a5507d00-6f4a-11ea-8f84-18b60adf87da.png)
