### ISSUE TITLE
Preference Issue with the Reservation Lava Block

### ISSUE THREAD

**Issue by jamrphy-bwd** [CentralAZ/Rock-CentralAZ#95]
### Prerequisites
* [ X ] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

ViewMode buttons on the Reservation Lava Block setting preferences causes error.

1. The ViewMode buttons (Day, Week, Month) set the preference on each click to their associated modes: 
![image](https://user-images.githubusercontent.com/44368014/47296773-4b26ec00-d5e1-11e8-8d5c-9c038c6c0fec.png)

2. The function SetFilterControls checks for this preference, and only assigns a default if the preference does not exist:
![image](https://user-images.githubusercontent.com/44368014/47296797-5da12580-d5e1-11e8-8fcc-c1700f68eeff.png)

3. Using the block more than once (i.e. with different configurations) will still set the preference for the Day, Week, or Month on button click. Since the configurations may differ between them (Day/Week view disabled, for example) the preference may be valid for one page, but not the other. 

Since SetFilterControls only assigns a default if the preference _does not exist_, the Configuration Error will show if the user last clicked a button on another page that is not supported with the current page's configuration.

### Steps to Reproduce

1. Create 2 pages that use this block
2. On one page, disable Day/Week Views.
3. One the other page, click "Day"
4. Navigate to the other page
5. See error

**Expected behavior:**

Default to a valid ViewMode if the preference is not valid for the current configuration

**Actual behavior:**

Configuration Error

### Versions

* **Rock Version:** Rock McKinley 7.5 (1.7.5.59)
* **Client Culture Setting:** en-US

**Comment by tcavaletto** [comment]
Fixed in 1.4: https://github.com/CentralAZ/Rock-CentralAZ/commit/79d94c1fa4e85578f350637effa817bf8d48a2ff
