### ISSUE TITLE
Consider more of an Event Management Tool than just Room Management 

### ISSUE THREAD

**Issue by MCoulterFBCN** [CentralAZ/Rock-CentralAZ#96]
# Feature Request

This tool is almost perfect for our needs to schedule Events.  We need a few additional fields or perhaps resource types to make this work.  

We want the ability to request special services for the event so that other individuals can be a part of the approval process.  For example, adding a field to ask for Child Care would trigger an approval request to our Preschool Ministry, or a request for Security, or Food Service, or Technology Support.

While fields on the primary form may address this, I'd almost like to see this as additional resources.  The only issue with using Resources for this now is that the Quantity field is required and that doesn't really work with this approach because availability is subjective in this case.

**Comment by tcavaletto** [comment]
This is currently out of scope for this project. We would recommend configuring additional workflows to fire based off of selected reservation attributes on the reservation. Also, many organizations do include special services as resources ( with corresponding approval groups managed by that ministry), if that route better fits your needs.
