### ISSUE TITLE
[RR] Plugin does not work after update to v8.3

### ISSUE THREAD

**Issue by marcierempel** [CentralAZ/Rock-CentralAZ#97]
I'm not sure if I'm putting in this request right. Our support people at KFS said I should put a note in here. We installed the Room Management plugin on our development database to play around with it and try it out. It was installed and working fine before we updated to v8.3. When I went in there after updating to v8.3, I installed the latest version of the plugin and it says it's installed, but not showing up anywhere.
![capture](https://user-images.githubusercontent.com/44587882/47678101-91062600-db86-11e8-843c-c22e9e6aac6c.JPG)

**Comment by marcierempel** [comment]
I am updating the title of this request. We've paid for the plugin and had it installed on our development site. It was working in v7.4 but since updating Rock to v8.3 the plugin doe not show up anywhere. In speaking with our support group at KFS they mentioned it may not have 'migrated' correctly? Can someone help me out here?

**Comment by nairdo** [comment]
What does KFS mean by did not 'migrate' correctly. Did they provide you with any details? 

In your System Information under Diagnostics does it list the plug-in:

com.centralaz.RoomManagement	ReservationType	19

**Comment by marcierempel** [comment]
Hi Nick – this is what KFS said (they have access to the files on our server) ‘It actually doesn't look like you even got any of the migrations for Room Management. You should reach out to Central - there should be a support or contact link in the documentation for that plugin - and let them know. They'll have to be the ones to set that straight’

I’ve attached a copy of the Diagnostics File from our development site. I don’t see it on there, but it says in the Rock Shop that I have it installed.

Marcie Rempel | EXECUTIVE ASSISTANT
Sherwood Park Alliance Church | spac.ca<http://www.spac.ca/>
780.467.8404 x420

**Comment by nairdo** [comment]
Hi Marcie, you should not publicly post you diagnostics file as it contains
enough sensitive information for a hacker to circumvent your system and
login as you. I'll remove the session cookie which is the most sensitive
item from there.

Based on the remainder of the information in your diagnostics file, it
looks like the plug-in has not been installed on your test system. In fact
it looks like your test system may have copied some data over from your
primary server which is making the Rock Shop think the plug-in is
installed.  (That should be pretty simple for KFS to troubleshoot, I'm
surprised they didn't troubleshoot that further for you.)

We're they involved with setting up your secondary/test system? If so, it
sounds like they've missed some steps.

Regards,
Nick

**Comment by marcierempel** [comment]
Thanks Nick, I forgot that email was posted back to this site. Is there a way to remove all of the diagnostics I sent you? I'll have KFS look at it again.
