### ISSUE TITLE
[RR]  In upgrading from Rock 7.4 to Rock 8.4 we lost connectivity between Events2HVAC and Rock.  The problem was due to a change in the Rest API to the Reservations Rest Controller > Get APIReservations/GetReservationsOccurrences... the value or security setting did not carry over from 7.4 to 8.4.  Once I reset security on this action, things began working correctly.

### ISSUE THREAD

**Issue by paultedder** [CentralAZ/Rock-CentralAZ#98]
### Description

In upgrading from Rock 7.4 to Rock 8.4 we lost connectivity between Events2HVAC and Rock. The problem was due to a change in the Rest API to the Reservations Rest Controller > Get APIReservations/GetReservationsOccurrences... the value or security setting did not carry over from 7.4 to 8.4. Once I reset security on this action, things began working correctly. #98

### Steps to Reproduce

**Expected behavior:**

**Actual behavior:**

A description of what actually happened.

### Versions

* **Rock Version:** [Enter Rock version here]
* **Client Culture Setting:** [Enter Client Culture here]

**Comment by tcavaletto** [comment]
Can't reproduce. This was probably due to an underlying Rock issue. If it happens again please open a Rock issue.
